name: build_werkkzeug3

on:
  workflow_dispatch: 
  push:
    branches: [ "master", "trace" ]
  pull_request:
    branches: [ "master", "trace" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: debug

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Werkkzeug
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;";
          msbuild 'werkkzeug3/wz3projects.sln' /p:configuration=debug /p:platform=x86
          

      - name: Build GenThree
        run: |
          $env:Path += ";" + $pwd.Path + "\yasm-1.3.0\;";
          msbuild 'genthree/genthree.sln' /p:configuration=debug /p:platform=Win32

      # - run: Get-ChildItem -Recurse
        
      #- name: Get Current Date
      #  id: date
      #  run: echo "CURRENT_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      #- name: Echo Current Date To Log
      #  run: echo ${{ env.CURRENT_DATE }}

      - name: Upload to GitHub Actions Artifact Storage
        uses: actions/upload-artifact@v6
        with:
          name: Kkrieger-Werkkzeug-#${{ github.run_number }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/werkkzeug3/example_cube/debug/example_cube.exe
            ${{ github.workspace }}/werkkzeug3/player_demo/debug/player_demo.exe
            ${{ github.workspace }}/werkkzeug3/player_intro/debug/player_intro.exe
            ${{ github.workspace }}/werkkzeug3/player_kkrieger/debug/player_kkrieger.exe
            ${{ github.workspace }}/werkkzeug3/shadercompile/debug/shadercompile.exe
            ${{ github.workspace }}/werkkzeug3/werkkzeug3/debug/werkkzeug3.exe
            ${{ github.workspace }}/werkkzeug3/data/*
            ${{ github.workspace }}/genthree/debug/genthree.exe
            ${{ github.workspace }}/genthree/data/*
            ${{ github.workspace }}/docs/*
          if-no-files-found: warn
